### ISSUE TITLE
ルートスケールの変更が反映されない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [KisaragiEffective/ResoniteImportHelper#103]
v0.1.10
![image](https://github.com/user-attachments/assets/9aa8d358-565b-420b-9e39-f87d23ac2be1)

機能要望です。
アバターのルートスケールを変更しているものが、glbでは等倍スケールに戻されてしまいます。
Resonite にインポートする上では不都合は少ないですが、スケールが適用されてるとうれしいです。
対応可能であればお願いしたいです。

**Comment by KisaragiEffective** [comment]
UniGLTFでも再現できたので、対処が難しい可能性があります。
