### ISSUE TITLE
RIHを入れたプロジェクトでVRCにアバターアップロードできない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [KisaragiEffective/ResoniteImportHelper#104]
v0.1.10

RIH を抜いたらアップロードできました

![image](https://github.com/user-attachments/assets/6bdab290-8a23-4cc8-8277-53a4244f36c2)
[logfile.txt](https://github.com/user-attachments/files/17005263/logfile.txt)

**Comment by KisaragiEffective** [comment]
メモ: `includePlatforms`
