### ISSUE TITLE
シピルカを変換しようとすると NullReferenceException

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [KisaragiEffective/ResoniteImportHelper#111]
v0.1.11

シーン上に (Clone) が生成されている

![image](https://github.com/user-attachments/assets/e1cef7ba-6ce3-40a8-824d-bcf848e60b34)

[logfile.txt](https://github.com/user-attachments/files/17061156/logfile.txt)

**Comment by KisaragiEffective** [comment]
😮

**Comment by KisaragiEffective** [comment]
> シーン上に (Clone) が生成されている

これは処理の最後でクローンを消すため正常です

>  シピルカを変換しようとすると NullReferenceException

VRC Avatar Descriptor > Eye Look > Eyes > Transformsのいずれかが空になっていませんか？

![](https://raw.githubusercontent.com/KisaragiEffective/ResoniteImportHelper/b063fc4d2a48cdb2bf5613489dbdae33a2c40e43/Doc%7E/EyeBoneFallbackFromVRChatAvatarDescriptor.png)

**Comment by blhsrwznrghfzpr** [comment]
Eye Look は設定されていませんでした

![image](https://github.com/user-attachments/assets/5b9b662d-fe27-4b7f-a3a8-6511b4d29cee)

v0.1.12 では問題なく動作しました
