### ISSUE TITLE
特定の衣装を着せていると例外を吐くことがある

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [KisaragiEffective/ResoniteImportHelper#149]
特定の衣装を着せている場合に失敗する。衣装を消すと成功する

[logfile.txt](https://github.com/user-attachments/files/17174395/logfile.txt)

**Comment by KisaragiEffective** [comment]
別の衣装でも発生しますか？それともその衣装固有の現象ですか？

**Comment by KisaragiEffective** [comment]
bisect for UniGLTF: https://github.com/vrm-c/UniVRM/blob/f8120fb22dade99ea8a9e03b77a3bbc2a4c79806/Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs#L61
Unity document: https://docs.unity3d.com/ScriptReference/AssetImporters.AssetImportContext.AddObjectToAsset.html

**Comment by KisaragiEffective** [comment]
可能性としては使われているテクスチャの名前がダブっているとうまく動作しない可能性があります。
RIHでは何も行っていないため、UniGLTFのバグの可能性があります。

**Comment by blhsrwznrghfzpr** [comment]
他の衣装で同じエラーが発生するものも発生しないものもありました

マテリアルやテクスチャ名を確認しましたが、ダブっては無さそうでした。念の為renameして実行してみましたが結果は変わりませんでした。

過去のバージョン(おそらくv0.1.4)では動作していたアバターが動かなくなっていました

生成した中間プレハブがマテリアルエラーになってました
![image](https://github.com/user-attachments/assets/e247b71e-0e7a-4126-be3a-803f29ef995f)

[logfile.txt](https://github.com/user-attachments/files/17177305/logfile.txt)

**Comment by konto250** [comment]
ルーシュカのデフォルト衣装でもエラーになりました
[logfile.txt](https://github.com/user-attachments/files/17190030/logfile.txt)

**Comment by KisaragiEffective** [comment]
ところで、この現象は0.1.12や0.1.13で再現しますか？

**Comment by blhsrwznrghfzpr** [comment]
v0.1.13では再現せず、正常に動作しました。
念のためログを取得しました
[logfile.txt](https://github.com/user-attachments/files/17203841/logfile.txt)

**Comment by KisaragiEffective** [comment]
次期リリースで解消見込みです。
