### ISSUE TITLE
Issues installing, 'lilTextureUtils' could not be found

### ISSUE THREAD

**Issue by Grinjr** [KisaragiEffective/ResoniteImportHelper#217]
I am having an issue installing this tool to try it out
```Library\PackageCache\io.github.kisaragieffective.resonite-import-helper@194833ba4b\Editor\Transform\Environment\LilToon\LilToonHandler.cs(173,37): error CS0246: The type or namespace name 'lilTextureUtils' could not be found (are you missing a using directive or an assembly reference?)```

I tried installing this in a new project and was also having the same issue. I thought it to be a dependency issue, and installed lilTextureUtil, but that didn't fix it either.

**Comment by KisaragiEffective** [comment]
I'm going to re-open this because I will work on specifying correct version range.

**Comment by KisaragiEffective** [comment]
However it is questionable, because the type `lilToon.liltextureUtils` should have contained since release 1.3: https://github.com/lilxyzw/lilToon/commit/13eea41c4a4b97cc432c16943cd9a9bb4889bb78#diff-f48427cf7064e648aef5d69c20b6a440a0dfb536df5aa49ed2b006a308ea72ceR185

**Comment by Grinjr** [comment]
I was able to reproduce this by following these steps:
1. Create a new project (created using the VRC Creator Companion)
2. Add liltoon 1.7.3 via unitypackage (not by UPM) https://github.com/lilxyzw/lilToon/releases/tag/1.7.3
3. Add ResoniteImportHelper via UPM

I noticed, however, that refreshing the project, if I use UPM to install liltoon rather than using the unitypackage, I no longer have any issues.
My guess is maybe something related to scope? The unitypackage installs liltoon to Assets, whereas the UPM installed it into Packages.
That being said, maybe listing liltoon as a required dependency would be a good idea as well.

**Comment by KisaragiEffective** [comment]
Could you send the reproduction project to me? I couldn't reproduce by those steps... 🤔

**Comment by Grinjr** [comment]
My apologies for the delay. Here's a [download to the project](https://mega.nz/file/UP0D3bya#L065WwZguUTBStv3hXk70qpu-1fOdudv_NDNQD_20CA)

**Comment by KisaragiEffective** [comment]
Thanks! I'll check it.

**Comment by KisaragiEffective** [comment]
I've identified the cause. The snippet should be surrounded by not only `RIH_HAS_HARMONY` but also `RIH_HAS_LILTOON`.

**Comment by KisaragiEffective** [comment]
ps. the fix will be included from next release.
