### ISSUE TITLE
ごちゃごちゃしたアバターが生成される

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [KisaragiEffective/ResoniteImportHelper#90]
v0.1.8

![image](https://github.com/user-attachments/assets/5cbd31e2-8d4b-4179-a0e0-11e4f4b9c569)

gltf自体は正常に生成されているが、シーン上に `model(Clone)(Clone)` が生成される

**Comment by KisaragiEffective** [comment]
regression found: https://github.com/KisaragiEffective/ResoniteImportHelper/commit/99d182bfd7223c1b0951fcaff4d2b99d28c0d8f0#diff-e9a3cebc46876483cb9bcd8cf76823c5144c6b92a4a1bef89220fe8bc547e219R32

**Comment by KisaragiEffective** [comment]
fixed by #93
