### ISSUE TITLE
Bake lilToon をするとテクスチャの抜けたアバターが生成される

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [KisaragiEffective/ResoniteImportHelper#91]
v0.1.8

![image](https://github.com/user-attachments/assets/8d60d5fd-4f37-4a29-a2c0-a2bff1ea438b)

テクスチャは生成されているが、マテリアルに割り当たっていなさそう

**Comment by KisaragiEffective** [comment]
0.1.9ではどうですか？

**Comment by blhsrwznrghfzpr** [comment]
0.1.9にしてみましたが変わらずです

やけにアセットが大量に生成されているのが気になります。
Consoleにはエラーは出ていませんでした

![image](https://github.com/user-attachments/assets/176ba27e-2f18-468e-975e-598ca319b041)

**Comment by KisaragiEffective** [comment]
> やけにアセットが大量に生成されているのが気になります。

これは最適化が甘いため ( #82 ) です。
